### ISSUE TITLE
Unable to connect to splicegraph

### ISSUE THREAD

**Issue by cgrisdale** [MD-Anderson-Bioinformatics/SpliceSeq#2]
Hi,
When I run SpliceSeq locally it's unable to connect to the splicegraph database. I get the error:
ERROR - java.sql.SQLException: Cannot communicate with the Ratway webapp: please check if the url is correct.

The URL it's trying is (from Configuration Panel):
jdbc:ratway://projects.insilico.us.com/Ratway/RW
This seems to match what is on the install page of the website for DBURL.

Command used:
java -jar SpliceSeq.jar

Any idea why I would get this error?

Thanks,
Cam

**Comment by mryaninsilico** [comment]
Cameron,

 

Thanks for the report.  We recently moved all of our bioinformatics apps to a cloud server and did not setup the sample SpliceSeq database.  If you want to process your own samples you will need to setup a local mysql database so you could take a look at that route: https://bioinformatics.mdanderson.org/public-software/spliceseq/installation/ (Creating and Initializing the SpliceSeq DB).

 

I will take a look at restoring the sample database so that works too.

 

Mike Ryan, PhD

In Silico Solutions

**Comment by ChrisWakefield** [comment]
Apparently solved since 2019.
